[2023-05-07T17:54:38.924+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.TransformData manual__2023-05-07T17:48:23.448865+00:00 [queued]>
[2023-05-07T17:54:38.930+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.TransformData manual__2023-05-07T17:48:23.448865+00:00 [queued]>
[2023-05-07T17:54:38.930+0000] {taskinstance.py:1331} INFO - Starting attempt 3 of 4
[2023-05-07T17:54:38.938+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): TransformData> on 2023-05-07 17:48:23.448865+00:00
[2023-05-07T17:54:38.945+0000] {standard_task_runner.py:57} INFO - Started process 400 to run task
[2023-05-07T17:54:38.951+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'TransformData', 'manual__2023-05-07T17:48:23.448865+00:00', '--job-id', '917', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmplik3s01l']
[2023-05-07T17:54:38.952+0000] {standard_task_runner.py:85} INFO - Job 917: Subtask TransformData
[2023-05-07T17:54:39.009+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.TransformData manual__2023-05-07T17:48:23.448865+00:00 [running]> on host f67ce86ae01d
[2023-05-07T17:54:39.073+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='TransformData' AIRFLOW_CTX_EXECUTION_DATE='2023-05-07T17:48:23.448865+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-07T17:48:23.448865+00:00'
[2023-05-07T17:54:39.127+0000] {warnings.py:110} WARNING - /opt/***/dags/src/transform.py:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  song_fact['date']=today

[2023-05-07T17:54:39.129+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

[2023-05-07T17:54:39.134+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/transform.py", line 39, in transform_data
    artist_dim=artist_dim[['artist_name','artist_id','genre']]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['genre'] not in index"
[2023-05-07T17:54:39.143+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=TransformData, execution_date=20230507T174823, start_date=20230507T175438, end_date=20230507T175439
[2023-05-07T17:54:39.150+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 917 for task TransformData ("['genre'] not in index"; 400)
[2023-05-07T17:54:39.203+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-07T17:54:39.224+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
