[2023-05-08T00:09:26.371+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T00:07:39.219723+00:00 [queued]>
[2023-05-08T00:09:26.376+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T00:07:39.219723+00:00 [queued]>
[2023-05-08T00:09:26.377+0000] {taskinstance.py:1331} INFO - Starting attempt 3 of 3
[2023-05-08T00:09:26.384+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): LoadData.LoadSongDim> on 2023-05-08 00:07:39.219723+00:00
[2023-05-08T00:09:26.390+0000] {standard_task_runner.py:57} INFO - Started process 1952 to run task
[2023-05-08T00:09:26.395+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.LoadSongDim', 'manual__2023-05-08T00:07:39.219723+00:00', '--job-id', '1635', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmp3xxshuiu']
[2023-05-08T00:09:26.396+0000] {standard_task_runner.py:85} INFO - Job 1635: Subtask LoadData.LoadSongDim
[2023-05-08T00:09:26.439+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T00:07:39.219723+00:00 [running]> on host fa349db4fc2f
[2023-05-08T00:09:26.496+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.LoadSongDim' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T00:07:39.219723+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T00:07:39.219723+00:00'
[2023-05-08T00:09:26.502+0000] {logging_mixin.py:149} INFO - 2023-05/song_dim.csv
[2023-05-08T00:09:26.513+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-05-08T00:09:26.514+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-05-08T00:09:26.834+0000] {logging_mixin.py:149} INFO -        song_name                 song_id  explicit  ...    tempo  valence  mode
0          WINGZ  7evQqGTWfKz8hIHzLVzneT     False  ...  170.025    0.120     0
1  lights (4444)  3PDNGdhCtiQemL14eKhCup      True  ...   89.982    0.428     1
2         softie  1bLEa8W1VVMFBIwp9hKYTL      True  ...  119.063    0.498     0
3    do me wrong  7H74AdiJYM7hh4SYGrq9xe     False  ...  174.960    0.396     0
4            HMU  2SWK4LJWLyev4yVYIVhjEV     False  ...   72.993    0.389     1

[5 rows x 15 columns]
[2023-05-08T00:09:26.835+0000] {logging_mixin.py:149} INFO - ['song_name', 'song_id', 'explicit', 'acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'key', 'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'mode']
[2023-05-08T00:09:26.843+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-05-08T00:09:26.886+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DependentObjectsStillExist: cannot drop table song_dim because other objects depend on it
DETAIL:  constraint song_artist_bridge_song_id_fkey on table song_artist_bridge depends on table song_dim
HINT:  Use DROP ... CASCADE to drop the dependent objects too.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/load.py", line 35, in upload_to_database
    df.to_sql(name=table, con=postgres_hook.get_sqlalchemy_engine(), if_exists='replace', index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1758, in to_sql
    dtype=dtype,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1650, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 860, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1810, in drop_table
    self.get_table(table_name, schema).drop()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 979, in drop
    bind._run_ddl_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3228, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2211, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 1106, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 81, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_ddl
    compiled,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table song_dim because other objects depend on it
DETAIL:  constraint song_artist_bridge_song_id_fkey on table song_artist_bridge depends on table song_dim
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE song_dim]
(Background on this error at: https://sqlalche.me/e/14/2j85)
[2023-05-08T00:09:26.900+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=Summer_Warped_ETL, task_id=LoadData.LoadSongDim, execution_date=20230508T000739, start_date=20230508T000926, end_date=20230508T000926
[2023-05-08T00:09:26.908+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1635 for task LoadData.LoadSongDim ((psycopg2.errors.DependentObjectsStillExist) cannot drop table song_dim because other objects depend on it
DETAIL:  constraint song_artist_bridge_song_id_fkey on table song_artist_bridge depends on table song_dim
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE song_dim]
(Background on this error at: https://sqlalche.me/e/14/2j85); 1952)
[2023-05-08T00:09:26.931+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T00:09:26.949+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
