[2023-05-08T15:49:19.925+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T04:41:38.915348+00:00 [queued]>
[2023-05-08T15:49:19.931+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T04:41:38.915348+00:00 [queued]>
[2023-05-08T15:49:19.932+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 4
[2023-05-08T15:49:19.940+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): LoadData.LoadCalendar> on 2023-05-08 04:41:38.915348+00:00
[2023-05-08T15:49:19.945+0000] {standard_task_runner.py:57} INFO - Started process 201 to run task
[2023-05-08T15:49:19.949+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.LoadCalendar', 'manual__2023-05-08T04:41:38.915348+00:00', '--job-id', '2384', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmpf1_eti3w']
[2023-05-08T15:49:19.949+0000] {standard_task_runner.py:85} INFO - Job 2384: Subtask LoadData.LoadCalendar
[2023-05-08T15:49:19.988+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T04:41:38.915348+00:00 [running]> on host 7b4753e133cb
[2023-05-08T15:49:20.042+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.LoadCalendar' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T04:41:38.915348+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T04:41:38.915348+00:00'
[2023-05-08T15:49:20.044+0000] {sql.py:262} INFO - Executing: 
                INSERT INTO calendar (date, month, monthname,dayofmonth,dayofweek,dayname,quarter)
                VALUES ('2023-05-08', 5, 'May',8,0,'Monday',2)
                 
[2023-05-08T15:49:20.052+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-05-08T15:49:20.089+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-05-08T15:49:20.098+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO calendar (date, month, monthname,dayofmonth,dayofweek,dayname,quarter)
                VALUES ('2023-05-08', 5, 'May',8,0,'Monday',2)
                 , parameters: None
[2023-05-08T15:49:20.101+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "calendar_pkey"
DETAIL:  Key (date)=(2023-05-08) already exists.

[2023-05-08T15:49:20.109+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=LoadData.LoadCalendar, execution_date=20230508T044138, start_date=20230508T154919, end_date=20230508T154920
[2023-05-08T15:49:20.117+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 2384 for task LoadData.LoadCalendar (duplicate key value violates unique constraint "calendar_pkey"
DETAIL:  Key (date)=(2023-05-08) already exists.
; 201)
[2023-05-08T15:49:20.160+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T15:49:20.178+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
