[2023-05-08T15:49:51.235+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T04:41:38.915348+00:00 [queued]>
[2023-05-08T15:49:51.241+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T04:41:38.915348+00:00 [queued]>
[2023-05-08T15:49:51.241+0000] {taskinstance.py:1331} INFO - Starting attempt 3 of 4
[2023-05-08T15:49:51.248+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): LoadData.LoadCalendar> on 2023-05-08 04:41:38.915348+00:00
[2023-05-08T15:49:51.253+0000] {standard_task_runner.py:57} INFO - Started process 217 to run task
[2023-05-08T15:49:51.257+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.LoadCalendar', 'manual__2023-05-08T04:41:38.915348+00:00', '--job-id', '2386', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmpcqyxmkn_']
[2023-05-08T15:49:51.257+0000] {standard_task_runner.py:85} INFO - Job 2386: Subtask LoadData.LoadCalendar
[2023-05-08T15:49:51.294+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T04:41:38.915348+00:00 [running]> on host 7b4753e133cb
[2023-05-08T15:49:51.349+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.LoadCalendar' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T04:41:38.915348+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T04:41:38.915348+00:00'
[2023-05-08T15:49:51.351+0000] {sql.py:262} INFO - Executing: 
                INSERT INTO calendar (date, month, monthname,dayofmonth,dayofweek,dayname,quarter)
                VALUES ('2023-05-08', 5, 'May',8,0,'Monday',2)
                 
[2023-05-08T15:49:51.358+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-05-08T15:49:51.397+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-05-08T15:49:51.407+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO calendar (date, month, monthname,dayofmonth,dayofweek,dayname,quarter)
                VALUES ('2023-05-08', 5, 'May',8,0,'Monday',2)
                 , parameters: None
[2023-05-08T15:49:51.408+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "calendar_pkey"
DETAIL:  Key (date)=(2023-05-08) already exists.

[2023-05-08T15:49:51.415+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=LoadData.LoadCalendar, execution_date=20230508T044138, start_date=20230508T154951, end_date=20230508T154951
[2023-05-08T15:49:51.421+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 2386 for task LoadData.LoadCalendar (duplicate key value violates unique constraint "calendar_pkey"
DETAIL:  Key (date)=(2023-05-08) already exists.
; 217)
[2023-05-08T15:49:51.471+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T15:49:51.489+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
