[2023-05-07T22:50:13.714+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.Load manual__2023-05-07T22:49:12.479459+00:00 [queued]>
[2023-05-07T22:50:13.720+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.Load manual__2023-05-07T22:49:12.479459+00:00 [queued]>
[2023-05-07T22:50:13.721+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 3
[2023-05-07T22:50:13.727+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): LoadData.Load> on 2023-05-07 22:49:12.479459+00:00
[2023-05-07T22:50:13.732+0000] {standard_task_runner.py:57} INFO - Started process 3292 to run task
[2023-05-07T22:50:13.736+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.Load', 'manual__2023-05-07T22:49:12.479459+00:00', '--job-id', '1435', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmpz_e53cv0']
[2023-05-07T22:50:13.736+0000] {standard_task_runner.py:85} INFO - Job 1435: Subtask LoadData.Load
[2023-05-07T22:50:13.771+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.Load manual__2023-05-07T22:49:12.479459+00:00 [running]> on host 31774baccecb
[2023-05-07T22:50:13.839+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.Load' AIRFLOW_CTX_EXECUTION_DATE='2023-05-07T22:49:12.479459+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-07T22:49:12.479459+00:00'
[2023-05-07T22:50:13.841+0000] {logging_mixin.py:149} INFO - 2023-05/song_dim.csv
[2023-05-07T22:50:13.850+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-05-07T22:50:13.851+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-05-07T22:50:14.022+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/load.py", line 28, in upload_to_database
    df1=pd.compat.StringIO(df)
AttributeError: module 'pandas.compat' has no attribute 'StringIO'
[2023-05-07T22:50:14.033+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=LoadData.Load, execution_date=20230507T224912, start_date=20230507T225013, end_date=20230507T225014
[2023-05-07T22:50:14.040+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1435 for task LoadData.Load (module 'pandas.compat' has no attribute 'StringIO'; 3292)
[2023-05-07T22:50:14.071+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-07T22:50:14.088+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
