[2023-05-08T04:31:04.382+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T00:55:07.270213+00:00 [queued]>
[2023-05-08T04:31:04.387+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T00:55:07.270213+00:00 [queued]>
[2023-05-08T04:31:04.388+0000] {taskinstance.py:1331} INFO - Starting attempt 4 of 6
[2023-05-08T04:31:04.395+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): LoadData.LoadCalendar> on 2023-05-08 00:55:07.270213+00:00
[2023-05-08T04:31:04.400+0000] {standard_task_runner.py:57} INFO - Started process 4360 to run task
[2023-05-08T04:31:04.404+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.LoadCalendar', 'manual__2023-05-08T00:55:07.270213+00:00', '--job-id', '2238', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmpk3lxfq8w']
[2023-05-08T04:31:04.404+0000] {standard_task_runner.py:85} INFO - Job 2238: Subtask LoadData.LoadCalendar
[2023-05-08T04:31:04.440+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T00:55:07.270213+00:00 [running]> on host a40687a10d43
[2023-05-08T04:31:04.492+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.LoadCalendar' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T00:55:07.270213+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T00:55:07.270213+00:00'
[2023-05-08T04:31:04.494+0000] {sql.py:262} INFO - Executing: 
                INSERT INTO calendar (date, month, monthname,dayofmonth,dayofweek,dayname,quarter)
                VALUES ('2023-05-08', 5, 'May',8,0,'Monday',2)
                 
[2023-05-08T04:31:04.501+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-05-08T04:31:04.544+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-05-08T04:31:04.553+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO calendar (date, month, monthname,dayofmonth,dayofweek,dayname,quarter)
                VALUES ('2023-05-08', 5, 'May',8,0,'Monday',2)
                 , parameters: None
[2023-05-08T04:31:04.555+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "calendar_pkey"
DETAIL:  Key (date)=(2023-05-08) already exists.

[2023-05-08T04:31:04.564+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=LoadData.LoadCalendar, execution_date=20230508T005507, start_date=20230508T043104, end_date=20230508T043104
[2023-05-08T04:31:04.571+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 2238 for task LoadData.LoadCalendar (duplicate key value violates unique constraint "calendar_pkey"
DETAIL:  Key (date)=(2023-05-08) already exists.
; 4360)
[2023-05-08T04:31:04.615+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T04:31:04.634+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
