[2023-05-08T04:31:35.463+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T00:55:07.270213+00:00 [queued]>
[2023-05-08T04:31:35.468+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T00:55:07.270213+00:00 [queued]>
[2023-05-08T04:31:35.468+0000] {taskinstance.py:1331} INFO - Starting attempt 5 of 6
[2023-05-08T04:31:35.476+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): LoadData.LoadCalendar> on 2023-05-08 00:55:07.270213+00:00
[2023-05-08T04:31:35.481+0000] {standard_task_runner.py:57} INFO - Started process 4372 to run task
[2023-05-08T04:31:35.484+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.LoadCalendar', 'manual__2023-05-08T00:55:07.270213+00:00', '--job-id', '2239', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmpmk5jvayh']
[2023-05-08T04:31:35.485+0000] {standard_task_runner.py:85} INFO - Job 2239: Subtask LoadData.LoadCalendar
[2023-05-08T04:31:35.520+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.LoadCalendar manual__2023-05-08T00:55:07.270213+00:00 [running]> on host a40687a10d43
[2023-05-08T04:31:35.573+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.LoadCalendar' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T00:55:07.270213+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T00:55:07.270213+00:00'
[2023-05-08T04:31:35.575+0000] {sql.py:262} INFO - Executing: 
                INSERT INTO calendar (date, month, monthname,dayofmonth,dayofweek,dayname,quarter)
                VALUES ('2023-05-08', 5, 'May',8,0,'Monday',2)
                 
[2023-05-08T04:31:35.582+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-05-08T04:31:35.620+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-05-08T04:31:35.629+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO calendar (date, month, monthname,dayofmonth,dayofweek,dayname,quarter)
                VALUES ('2023-05-08', 5, 'May',8,0,'Monday',2)
                 , parameters: None
[2023-05-08T04:31:35.631+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "calendar_pkey"
DETAIL:  Key (date)=(2023-05-08) already exists.

[2023-05-08T04:31:35.639+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=LoadData.LoadCalendar, execution_date=20230508T005507, start_date=20230508T043135, end_date=20230508T043135
[2023-05-08T04:31:35.645+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 2239 for task LoadData.LoadCalendar (duplicate key value violates unique constraint "calendar_pkey"
DETAIL:  Key (date)=(2023-05-08) already exists.
; 4372)
[2023-05-08T04:31:35.696+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T04:31:35.717+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
