[2023-05-07T22:39:03.849+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.Load manual__2023-05-07T22:38:31.867949+00:00 [queued]>
[2023-05-07T22:39:03.859+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.Load manual__2023-05-07T22:38:31.867949+00:00 [queued]>
[2023-05-07T22:39:03.860+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 3
[2023-05-07T22:39:03.870+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): LoadData.Load> on 2023-05-07 22:38:31.867949+00:00
[2023-05-07T22:39:03.906+0000] {standard_task_runner.py:57} INFO - Started process 2298 to run task
[2023-05-07T22:39:03.914+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.Load', 'manual__2023-05-07T22:38:31.867949+00:00', '--job-id', '1259', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmp6516gyb4']
[2023-05-07T22:39:03.915+0000] {standard_task_runner.py:85} INFO - Job 1259: Subtask LoadData.Load
[2023-05-07T22:39:03.971+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.Load manual__2023-05-07T22:38:31.867949+00:00 [running]> on host 31774baccecb
[2023-05-07T22:39:04.026+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.Load' AIRFLOW_CTX_EXECUTION_DATE='2023-05-07T22:38:31.867949+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-07T22:38:31.867949+00:00'
[2023-05-07T22:39:04.027+0000] {logging_mixin.py:149} INFO - 2023-05/song_dim.csv
[2023-05-07T22:39:04.034+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-05-07T22:39:04.035+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-05-07T22:39:04.203+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/load.py", line 28, in upload_to_database
    print(df.type)
AttributeError: 'str' object has no attribute 'type'
[2023-05-07T22:39:04.212+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=LoadData.Load, execution_date=20230507T223831, start_date=20230507T223903, end_date=20230507T223904
[2023-05-07T22:39:04.218+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1259 for task LoadData.Load ('str' object has no attribute 'type'; 2298)
[2023-05-07T22:39:04.244+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-07T22:39:04.261+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
